### ISSUE TITLE
Strange error with get_it_mixin

### ISSUE THREAD

**Issue by thommy66** [escamoteur/get_it_mixin#19]
I installed latest versions of AndroidStudio, Flutter, plugins etc. Since I had different versions of AndroidStudio I cleaned up everything and re-installed from scratch. I started replacing Stateful with Stateless Widgets and added `get_it_mixin`. When building the project I get the following error:
```
Launching lib/main.dart on iPhone 13 in debug mode...
Running Xcode build...
Xcode build done.                                           10.5s
Debug service listening on ws://127.0.0.1:53118/H_LQeT1mgxM=/ws
Syncing files to device iPhone 13...
../../../../Applications/flutter/.pub-cache/hosted/pub.dartlang.org/get_it_mixin-3.1.3/lib/src/mixin_state.dart:495:7: Warning: Operand of null-aware operation '!' has type 'void Function(BuildContext, AsyncSnapshot<R?>, void Function())' which excludes null.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../../../Applications/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'AsyncSnapshot' is from 'package:flutter/src/widgets/async.dart' ('../../../../Applications/flutter/packages/flutter/lib/src/widgets/async.dart').
      handler!(_element!, watch.lastValue!, watch.dispose);
      ^
```
The app starts but does not work since I implemented `get_it_mixin` on my home screen.

It happens also with *Android Simulator*, e.g. Pixel 4.  Flutter doctor does not report any issues:
```
[Google] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-x64, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)

• No issues found!
```
I tried `flutter clean` but that didn't help.

Any idea what is wrong here?

**Comment by thommy66** [comment]
I did some more research since this is a showstopper for me.

The impact of this warning / error is as follows:
`notifyListeners()` does somehow **not** work. I use it in a Scaffold with a BottomNavigationBar. This requires to detect if the selected (tab)item changes. The `build` method of the widget is **not immediately** called. Sometimes it does rebuild **after one minute or so**!! Really strange.

So I have loaded a very old project which I used to learn how to work with `get_it_mixin`. That is extremely simple and has no other packages than `get_it / get_it_mixin`. It uses version 1.5.1. There no error is displayed and `notifyListeners()` works just fine. 

Looks like there is a problem with version 3.1.3. I tried to use an older version like 1.5.1 but that does not work because of dependencies. Also Version 2.0.0 seems to be to old. I also tried 3.1.0 but there the same error is shown. To me this looks like a dependency problem of recent version with latest versions of Android Studio and the Flutter SDK.

This is my pubspec.yaml file with the latest version and the error shown above:

```
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bottom_navy_bar: ^6.0.0
  get_it: ^7.2.0
  get_it_mixin: ^3.1.3
  servicestack: ^2.0.0
  font_awesome_flutter: ^9.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.3
  uuid: ^3.0.4
  equatable: ^2.0.3
  intl: ^0.17.0
  tuple: ^2.0.0
  flutter_layout_grid: ^1.0.3
  device_info_plus: ^3.0.1
  network_info_plus: ^2.0.2
  flutter_slidable: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
```

I also cleaned the public cache with `flutter pub cache clean` and then ran `flutter pub get` to make sure I do not have corrupted stuff in my `.pub-cache` folder. However this did not help. 

I have no idea what else I could try....
